### PR TITLE
Cut new release

### PR DESCRIPTION
**Pull request by mjcheetham**
**Changes:**

- Move to .NET Framework 4.7.2 on Windows (#283)
- Move to .NET 5.0 on macOS and Linux (#288)
- Auto-detect on-premises/self-hosted providers via HTTP headers (#262)
- Use the user's default web browser for Microsoft authentication on macOS and drop the native helper (#274, #277)
- Trivially fix the macOS native helper crashes by deleting it 😅 (#264)
- Share the MSAL token cache with Microsoft developer tools on macOS as we already do on Windows (#275)
- Support `git-credential-cache` as a credential backing store on Linux (#287)
- Support for the `NO_PROXY` option to bypass the proxy for certain addresses (#299, #297)
- Use [`System.CommandLine`](https://github.com/dotnet/command-line-api) to handle our command line parsing and allow host providers to offer custom commands (#273)
- Fix a bug with host provider disposal (#272)
- Fix problems with resolving the executable file path on Linux (#298, #229, #252)
- Documentation fixes and improvements (#278, #265, #263)

**Thanks to our contributors ❤️:**

- @4brunu
- @AlexanderLanin
- @johnemau
- @NN---

### CODE REVIEW

**Comment by mjcheetham** [comment]
I like the PR number of 3️⃣ 0️⃣ 0️⃣ ! 🎉

**Comment by dscho** [comment]
> 
> 
> I like the PR number of 3️⃣ 0️⃣ 0️⃣ ! 🎉

image

**Review by dscho — APPROVED** [review]
Rubber-stamping this, as all of the changes have been reviewed already before they were integrated into the main branch.

**Comment by Sokhanetaze80** [comment]
12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr

**Pull request merged**
